snake_client.exe : net_control.c snake_client.c snake_client.h snake_control.c
	gcc snake_client.c snake_control.c net_control.c -o snake_client.exe -std=c99 -lmingw32 -lSDLmain -lSDL -lwsock32 -mwindows
